#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for crewconnect project
# Feature: Mark all messages as read

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
PROJECT_ROOT="/home/michael/Dokumente/GitHub/crewconnect01"
MAIN_PORT=3000
MAIN_DEV_COMMAND="npm run dev"

# Change to project root
cd "$PROJECT_ROOT"

echo -e "${BLUE}Project Root: $PROJECT_ROOT${NC}"
echo ""

# ============================================
# CHECK PREREQUISITES
# ============================================

echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm: $(npm --version)${NC}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

echo ""

# ============================================
# START FRONTEND SERVICE
# ============================================

echo -e "${BLUE}Starting Main Service (React Frontend)...${NC}"
echo "Port: $MAIN_PORT"
echo "Command: $MAIN_DEV_COMMAND"
echo ""

# Start the development server
$MAIN_DEV_COMMAND &
MAIN_PID=$!

# Wait for service to be ready
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null && ! lsof -i ":$port" 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${YELLOW}$name startup check timed out (server may still be starting)${NC}"
            return 0
        fi
        sleep 1
    done
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

wait_for_service $MAIN_PORT "Main Service"

echo ""

# ============================================
# SUMMARY
# ============================================

echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo -e "  Main (Frontend): ${GREEN}http://localhost:$MAIN_PORT${NC}"
echo ""
echo "Project: crewconnect"
echo "Feature: Mark all messages as read"
echo ""
echo "Development commands:"
echo "  - View logs: Check browser console"
echo "  - Stop services: Press Ctrl+C"
echo "  - Build for production: npm run build"
echo ""
echo "To view the application:"
echo "  Open http://localhost:$MAIN_PORT in your browser"
echo ""
echo "Process IDs:"
echo "  Main: $MAIN_PID"
echo ""
echo "========================================"
